1.Create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function:

In [1]:
import numpy as np

vector = np.arange(1, 11) + 1
print(vector)

[ 2  3  4  5  6  7  8  9 10 11]


2.Create a 10 × 10 matrix A in which A[i][j] = i + j:

In [2]:
matrix = vector.reshape(-1, 1) + vector.reshape(1, -1)
print(matrix)

[[ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]
 [12 13 14 15 16 17 18 19 20 21]
 [13 14 15 16 17 18 19 20 21 22]]


3.Create a fake "data set" with 50 examples, each with five dimensions:

In [3]:
import numpy.random as npr

data = np.exp(npr.randn(50, 5))

4.Compute the mean and standard deviation of each column:

In [4]:
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

print("Mean of each column:", mean)
print("Standard deviation of each column:", std)

Mean of each column: [1.37707762 1.55847151 1.20336563 1.36847131 2.02237667]
Standard deviation of each column: [1.20870086 1.76399895 0.79298168 1.47419383 2.21954787]


5.Standardize the data matrix by subtracting the mean off of each column and dividing each column by its standard deviation:

In [5]:
normalized = (data - mean) / std
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

print("Mean of each column of normalized matrix:", normalized_mean)
print("Standard deviation of each column of normalized matrix:", normalized_std)

Mean of each column of normalized matrix: [ 4.32986980e-17  2.03170814e-16 -6.75015599e-16 -3.78030940e-16
 -2.59792188e-16]
Standard deviation of each column of normalized matrix: [1. 1. 1. 1. 1.]
